site_name: Louisiana Maps Georeferencing Commons
site_description: 'Documentation for Old Insurance Maps'
site_author: 'mradamcox'
site_url: https://oldinsurancemaps.net

# repo_url: https://github.com/Siphalor/mkdocs-custommill
toc_info: true

dev_addr: '127.0.0.1:8001'

nav:
  - Home: home.md
  - Guide: guide.md
  - Content: content.md
  - About: about.md

theme:
  name: 'custommill'
  home: home
  main_color: '#123B4F'
  lighter_gray: '#EAE0C1'

markdown_extensions:
  - admonition
  - pymdownx.tabbed

extra:
  version: 1.1
  nav_links:
  - icon: home
    text: Go to LaMGC site
    url: https://oldinsurancemaps.net
  - icon: book
    text: LOC Sanborn Maps
    url: https://loc.gov/collections/sanborn-maps